"""001_create_core_tables

Revision ID: 0b82792ecc59
Revises: 
Create Date: 2026-03-07 18:51:55.690612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b82792ecc59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('pdf_digital', 'pdf_scanned', 'image_png', 'image_jpg', name='file_type_enum'), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('queued', 'extracting', 'cleaning', 'analyzing', 'complete', 'failed', name='job_status_enum'), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_created', 'analysis_jobs', ['created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_jobs_status', 'analysis_jobs', ['status'], unique=False)
    op.create_table('extraction_results',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=40), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_extraction_job', 'extraction_results', ['job_id'], unique=False)
    op.create_table('sentiment_results',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('vader_positive', sa.Float(), nullable=False),
    sa.Column('vader_negative', sa.Float(), nullable=False),
    sa.Column('vader_neutral', sa.Float(), nullable=False),
    sa.Column('vader_compound', sa.Float(), nullable=False),
    sa.Column('bert_positive', sa.Float(), nullable=True),
    sa.Column('bert_negative', sa.Float(), nullable=True),
    sa.Column('final_positive_pct', sa.Float(), nullable=False),
    sa.Column('final_negative_pct', sa.Float(), nullable=False),
    sa.Column('final_neutral_pct', sa.Float(), nullable=False),
    sa.Column('final_compound', sa.Float(), nullable=False),
    sa.Column('verdict', sa.Enum('GOOD', 'BAD', 'NEUTRAL', name='verdict_enum'), nullable=False),
    sa.Column('verdict_confidence', sa.Float(), nullable=False),
    sa.Column('raw_scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_sentiment_job', 'sentiment_results', ['job_id'], unique=False)
    op.create_index('idx_sentiment_verdict', 'sentiment_results', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sentiment_verdict', table_name='sentiment_results')
    op.drop_index('idx_sentiment_job', table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index('idx_extraction_job', table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index('idx_jobs_status', table_name='analysis_jobs')
    op.drop_index('idx_jobs_created', table_name='analysis_jobs', postgresql_using='btree')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
